export const IMG_CDN_URL = 
"https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/";

export const restaurantList = [
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "568066",
        name: "Udipi's Upahar",
        uuid: "65210dea-0e01-4f1a-ab64-d93828937bec",
        city: "3",
        area: "Madhapur",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "o2au1zgaz3ik6fakavgb",
        cuisines: ["South Indian", "North Indian", "Chinese", "Biryani"],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "₹200 FOR TWO",
        deliveryTime: 33,
        minDeliveryTime: 33,
        maxDeliveryTime: 33,
        slaString: "33 MINS",
        lastMileTravel: 3.9000000953674316,
        slugs: {
          restaurant: "udipi’s-upahar-madhapur-madhapur",
          city: "hyderabad",
        },
        cityState: "3",
        address:
          "Minicipal No:1-90/7/B/49,PLOT NO:120/16 (old:10), Sy no 78,Patrika Nagar, Madhapur,Serlingampally Circle No 20, Hyderabad, Telangana-500081",
        locality: "Madhapur",
        parentId: 1061,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3400,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3400,
          message: "",
          title: "Delivery Charge",
          amount: "3400",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "cid=5665232~p=1~eid=00000185-d285-1625-090a-eb2b00630105",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "3.9 kms",
        hasSurge: false,
        sla: {
          restaurantId: "568066",
          deliveryTime: 33,
          minDeliveryTime: 33,
          maxDeliveryTime: 33,
          lastMileTravel: 3.9000000953674316,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.3",
        totalRatings: 1000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "575804",
        name: "Varalakshmi Tiffins",
        uuid: "d116252d-ea0d-4959-96f3-a7f9b995daee",
        city: "3",
        area: "Ameerpet",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "8523266de1213e8ea57e5df4eedf747e",
        cuisines: ["South Indian"],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "₹200 FOR TWO",
        deliveryTime: 34,
        minDeliveryTime: 34,
        maxDeliveryTime: 34,
        slaString: "34 MINS",
        lastMileTravel: 5,
        slugs: {
          restaurant: "varalakshmi-tiffins-ameerpet-ameerpet-2",
          city: "hyderabad",
        },
        cityState: "3",
        address:
          "H No: 79/B, Community Hall Road, Opp.SBI Bank, SR Nagar, Hyderabad , Khairatabad Circle No.17, Hyderabad, Telangana-500038",
        locality: "Oppsbi Bank",
        parentId: 6482,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "40% off",
          shortDescriptionList: [
            {
              meta: "40% off | Use TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "40% off up to ₹80 | Use code TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "40% OFF",
          shortDescriptionList: [
            {
              meta: "Use TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "40% off up to ₹80 | Use code TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 4800,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 4800,
          message: "",
          title: "Delivery Charge",
          amount: "4800",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "5 kms",
        hasSurge: false,
        sla: {
          restaurantId: "575804",
          deliveryTime: 34,
          minDeliveryTime: 34,
          maxDeliveryTime: 34,
          lastMileTravel: 5,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.4",
        totalRatings: 1000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "5974",
        name: "Bheema's",
        uuid: "b9f4e99f-5958-49d4-b9fa-a169beada530",
        city: "3",
        area: "Shaikpet",
        totalRatingsString: "5000+ ratings",
        cloudinaryImageId: "wrlcwarzitxcdrtqv4ix",
        cuisines: ["South Indian"],
        tags: [],
        costForTwo: 15000,
        costForTwoString: "₹150 FOR TWO",
        deliveryTime: 57,
        minDeliveryTime: 57,
        maxDeliveryTime: 57,
        slaString: "57 MINS",
        lastMileTravel: 7.199999809265137,
        slugs: {
          restaurant: "bheemas-manikonda",
          city: "hyderabad",
        },
        cityState: "3",
        address: "Manikonda Rd, OU Colony, Shaikpet, Hyderabad, Telangana 500008",
        locality: "OU Colony",
        parentId: 1841,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "40% off",
          shortDescriptionList: [
            {
              meta: "40% off | Use GUILTFREEJAN",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "40% off up to ₹100 | Use code GUILTFREEJAN",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "40% OFF",
          shortDescriptionList: [
            {
              meta: "Use GUILTFREEJAN",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "40% off up to ₹100 | Use code GUILTFREEJAN",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 6200,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 6200,
          message: "",
          title: "Delivery Charge",
          amount: "6200",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 1,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "7.1 kms",
        hasSurge: false,
        sla: {
          restaurantId: "5974",
          deliveryTime: 57,
          minDeliveryTime: 57,
          maxDeliveryTime: 57,
          lastMileTravel: 7.199999809265137,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "IT_IS_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.3",
        totalRatings: 5000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "126322",
        name: "Om Sai Ram Tiffins",
        uuid: "ba370691-4938-4bf3-941a-5761009f9f48",
        city: "3",
        area: "Sri Sai Nagar",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "in13z1kkmqk70vsikqns",
        cuisines: ["South Indian"],
        tags: [],
        costForTwo: 10000,
        costForTwoString: "₹100 FOR TWO",
        deliveryTime: 40,
        minDeliveryTime: 40,
        maxDeliveryTime: 40,
        slaString: "40 MINS",
        lastMileTravel: 2.4000000953674316,
        slugs: {
          restaurant: "om-sai-ram-tiffins-madhapur-madhapur",
          city: "hyderabad",
        },
        cityState: "3",
        address: "H No. 1-98/21/L, Jai Hind Enclave, Madhapur, Hyderabad-500081",
        locality: "Madhapur",
        parentId: 18954,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 2700,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 2700,
          message: "",
          title: "Delivery Charge",
          amount: "2700",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "cid=5761520~p=4~eid=00000185-d285-1625-090a-eb2c00630428",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "2.4 kms",
        hasSurge: false,
        sla: {
          restaurantId: "126322",
          deliveryTime: 40,
          minDeliveryTime: 40,
          maxDeliveryTime: 40,
          lastMileTravel: 2.4000000953674316,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.3",
        totalRatings: 1000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "34634",
        name: "Shah Ghouse Cafe & Restaurant",
        uuid: "b01410a9-830a-45c8-b128-7358eea26f5b",
        city: "3",
        area: "Tolichowki",
        totalRatingsString: "10000+ ratings",
        cloudinaryImageId: "ks4d93rjtcbitkzkbqx0",
        cuisines: ["Biryani", "North Indian", "Chinese", "Mughlai", "Tandoor"],
        tags: [],
        costForTwo: 35000,
        costForTwoString: "₹350 FOR TWO",
        deliveryTime: 43,
        minDeliveryTime: 43,
        maxDeliveryTime: 43,
        slaString: "43 MINS",
        lastMileTravel: 9.300000190734863,
        slugs: {
          restaurant: "shah-ghouse-cafe-restaurant-tolichowki-tolichowki",
          city: "hyderabad",
        },
        cityState: "3",
        address:
          "Opposite SA Imperial Gardens, Near RTA Office, Tolichowki, Hyderabad",
        locality: "Tolichowki",
        parentId: 18992,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "20% off",
          shortDescriptionList: [
            {
              meta: "20% off | Use TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "20% off up to ₹50 | Use code TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "20% OFF",
          shortDescriptionList: [
            {
              meta: "Use TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "20% off up to ₹50 | Use code TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 7800,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 7800,
          message: "",
          title: "Delivery Charge",
          amount: "7800",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 1,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "9.3 kms",
        hasSurge: false,
        sla: {
          restaurantId: "34634",
          deliveryTime: 43,
          minDeliveryTime: 43,
          maxDeliveryTime: 43,
          lastMileTravel: 9.300000190734863,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "IT_IS_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.1",
        totalRatings: 10000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "41001",
        name: "Sri Raghavendra Pure Veg",
        uuid: "7392e43a-1e58-463a-8ae2-84a78196f6bd",
        city: "3",
        area: "Kukatpally",
        totalRatingsString: "5000+ ratings",
        cloudinaryImageId: "xdmyhxsxt3bpy5g8q3c4",
        cuisines: ["South Indian", "Andhra"],
        tags: [],
        costForTwo: 15000,
        costForTwoString: "₹150 FOR TWO",
        deliveryTime: 34,
        minDeliveryTime: 34,
        maxDeliveryTime: 34,
        slaString: "34 MINS",
        lastMileTravel: 5,
        slugs: {
          restaurant:
            "sri-raghavendra-pure-veg-kukatpally-nizampet-pragathi-nagar",
          city: "hyderabad",
        },
        cityState: "3",
        address:
          "M.C.K 15-31-111-1-71/324, Ramya Centre, Ramya Ground, K.P.H.B Colony, Kukatpally, Hyderabad - 500072",
        locality: "K P H B Phase 3",
        parentId: 194264,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "20% off",
          shortDescriptionList: [
            {
              meta: "20% off | Use PARTY",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "20% off | Use code PARTY",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "20% OFF",
          shortDescriptionList: [
            {
              meta: "Use PARTY",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "20% off | Use code PARTY",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 4800,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 4800,
          message: "",
          title: "Delivery Charge",
          amount: "4800",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 1,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "5 kms",
        hasSurge: false,
        sla: {
          restaurantId: "41001",
          deliveryTime: 34,
          minDeliveryTime: 34,
          maxDeliveryTime: 34,
          lastMileTravel: 5,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "IT_IS_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.2",
        totalRatings: 5000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "73758",
        name: "Sai Darshini Tiffins",
        uuid: "edc05ee6-34ef-4dfa-931f-e6d2db85ffa8",
        city: "3",
        area: "Czech Colony",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "eeymdtpdkgxxru90w27o",
        cuisines: ["South Indian"],
        tags: [],
        costForTwo: 15000,
        costForTwoString: "₹150 FOR TWO",
        deliveryTime: 27,
        minDeliveryTime: 27,
        maxDeliveryTime: 27,
        slaString: "27 MINS",
        lastMileTravel: 4.599999904632568,
        slugs: {
          restaurant: "sai-darshini-tiffins-sanath-nagar-ameerpet",
          city: "hyderabad",
        },
        cityState: "3",
        address:
          "Opp: Axis Bank Atm, Vengal Rao Nagar Rd, Hyderabad, Telangana 500038",
        locality: "Czech Colony",
        parentId: 11825,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: "10% off",
          shortDescriptionList: [
            {
              meta: "10% off | Use TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "10% off up to ₹40 | Use code TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        aggregatedDiscountInfoV2: {
          header: "10% OFF",
          shortDescriptionList: [
            {
              meta: "Use TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          descriptionList: [
            {
              meta: "10% off up to ₹40 | Use code TRYNEW",
              discountType: "Percentage",
              operationType: "RESTAURANT",
            },
          ],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 4100,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 4100,
          message: "",
          title: "Delivery Charge",
          amount: "4100",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "cid=5668389~p=7~eid=00000185-d285-1625-090a-eb2d0063076d",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "4.5 kms",
        hasSurge: false,
        sla: {
          restaurantId: "73758",
          deliveryTime: 27,
          minDeliveryTime: 27,
          maxDeliveryTime: 27,
          lastMileTravel: 4.599999904632568,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.3",
        totalRatings: 1000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "571904",
        name: "SRI SAI DARSHINI",
        uuid: "1b101dd2-9da5-4180-9f46-ac5d9da7c575",
        city: "3",
        area: "Banjara Hills",
        totalRatingsString: "Too Few Ratings",
        cloudinaryImageId: "qnyeve7qzpcrx9iwmwyr",
        cuisines: ["South Indian", "Chinese", "North Indian"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 43,
        minDeliveryTime: 43,
        maxDeliveryTime: 43,
        slaString: "43 MINS",
        lastMileTravel: 8.399999618530273,
        slugs: {
          restaurant: "sri-sai-siri-darshini-banjara-hills-banjara-hills",
          city: "hyderabad",
        },
        cityState: "3",
        address:
          "6-3-650, somajiguda , hyderabad-500041,  Khairatabad Circle No.17 , Hyderabad,  Telangana - 500041",
        locality: "Somajiguda",
        parentId: 19884,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 7100,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 7100,
          message: "",
          title: "Delivery Charge",
          amount: "7100",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 1,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "8.3 kms",
        hasSurge: false,
        sla: {
          restaurantId: "571904",
          deliveryTime: 43,
          minDeliveryTime: 43,
          maxDeliveryTime: 43,
          lastMileTravel: 8.399999618530273,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "IT_IS_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "--",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
  ];